services:
  config-server:
    build:
      context: .
      dockerfile: dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - SERVER_PORT=${SERVER_PORT}
      - APP_SECURITY_USER_NAME=${APP_SECURITY_USER_NAME}
      - APP_SECURITY_USER_PASSWORD=${APP_SECURITY_USER_PASSWORD}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    restart: unless-stopped
    network_mode: host