server:
    port: ${SERVER_PORT}
spring:
    cloud:
        config:
            server:
                git:
                    uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
                    force-pull: true
                    default-label: main
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
app:
    security:
        user:
            name: ${APP_SECURITY_USER_NAME}
            password: ${APP_SECURITY_USER_PASSWORD}